package com.miftah.core.utils

object Constants {
    const val DATA_STORAGE_PREFERENCE_USERNAME = "DATA_STORAGE_PREFERENCE_USERNAME"
    const val DATA_STORAGE_PREFERENCE_USER_ID = "DATA_STORAGE_PREFERENCE_USER_ID"
    const val DATA_STORAGE_PREFERENCE_TOKEN = "DATA_STORAGE_PREFERENCE_TOKEN"
    const val DATA_STORAGE_PREFERENCE_IS_LOGIN = "DATA_STORAGE_PREFERENCE_IS_LOGIN"
}