package com.miftah.core.utils

object Constants {
    const val DATA_STORAGE_PREFERENCE_USERNAME = "DATA_STORAGE_PREFERENCE_USERNAME"
    const val DATA_STORAGE_PREFERENCE_USER_ID = "DATA_STORAGE_PREFERENCE_USER_ID"
    const val DATA_STORAGE_PREFERENCE_TOKEN = "DATA_STORAGE_PREFERENCE_TOKEN"
    const val DATA_STORAGE_PREFERENCE_IS_LOGIN = "DATA_STORAGE_PREFERENCE_IS_LOGIN"

    const val STORY_ID = "STORY_ID"
    const val STORY_DESCRIPTION = "STORY_DESCRIPTION"
    const val STORY_PHOTO_URL = "STORY_PHOTO_URL"
    const val STORY_TITLE = "STORY_TITLE"
}